# Generated by Django 2.1.4 on 2019-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0002_auto_20190525_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='sid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='信号强度号'),
        ),
    ]
