# Generated by Django 2.1.4 on 2019-05-28 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0004_auto_20190525_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='指纹 AP 号')),
                ('apid', models.IntegerField(verbose_name='指纹 AP 编号')),
                ('top', models.CharField(max_length=4, verbose_name='坐标-顶部')),
                ('left', models.CharField(max_length=4, verbose_name='坐标-左侧')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='apnum',
        ),
        migrations.AddField(
            model_name='apoint',
            name='lid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Pos.Location'),
        ),
    ]
